name: Build and Release

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: catimg-linux
            asset_name: catimg-linux
          - os: windows-latest
            artifact_name: catimg-windows.exe
            asset_name: catimg-windows.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run compile

    - name: Rename executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: mv catimg ${{ matrix.artifact_name }}

    - name: Rename executable (Windows)
      if: matrix.os == 'windows-latest'
      run: mv catimg.exe ${{ matrix.artifact_name }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}
        retention-days: 30
